// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "sword":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...............bbb..............
..............bdddb.............
.............bdbbbd.............
............bbbbbbbdb...........
............bbddddddb...........
............cdbdddbbc...........
............ebdbbbdce...........
............eeefccee............
............ceeeeeee............
............ceeeeeee............
............ceeeeeee............
.............eeeeeee............
............76eeeee67...........
...........6766eee6676..........
...........68e76867866..........
.............e7eee7ce...........
.............e6eee6ef...........
.............eeeeeeef...........
.............eeeeeecf...........
.............eeeeeeff...........
`;
            case "image2":
            case "swordd":return img`
........................
........................
..........bbbb..........
........bbddddbb........
.......bddbbbbddb.......
......bdbbddddbbdb......
.....bdbbdbbbbdbbdb.....
.....bdbdbddddbdbdb.....
.....cdbbdbbbbdbbdc.....
.....cbdbbddddbbdbc.....
.....efbddbbbbddbce.....
.....eeffbddddbccee.....
.....eeeeffcccceee......
.....ceeeeeeeeeeee......
.....ceeeeeeeeeeee......
.....feeeeeeeeeeee......
.....cceeeeeeeeeee......
......feeeeeeeeeee......
.....6fceeeeeeeeee6.....
....6776eeeeeeeee676....
...6777666eeee6666776...
..67768e67766777667776..
...668ee7768867788666...
......ee77eeee77ecee....
......ee6eeeeee6eef.....
......eeeeeeeeeeeef.....
......eeeeeeeeeeeef.....
......eeeeeeeeeeecf.....
......ceeeeeeeeeecf.....
......ceeeeeeeeeeff.....
......feeeeeeeeeefe.....
.....6feeeeeeeeeef6.....
....6776eeeeeeeee676....
...6777666eeee6667776...
..6776ee67777777667776..
...668ee7768867788666...
......ee77eeee67ee......
......ee6eeeeee6ce......
......eefeeeeeeece......
......eeceeeeeeece......
......eeceeeeeeefe......
......eeceeeeeeefe......
......eeeeeeeeeefe......
......eeeeeeeeeece......
.....6eeeeeeeeeece6.....
....6776eeeeeeeee676....
...6776666eeee6766776...
..6776ee77777777667776..
...668ce7768867788666...
......ce77eeee67ee......
......ce6eeeeee6ee......
......ceeeeeeeeeee......
......fcceeeeeecee......
......fccceeececce......
......fcceeecceccc......
......fccceecceccc......
......fccccceceecc......
.....6fccccccccccf6.....
....6776ccccccccc676....
...6776676cccc6766776...
..6776cc77777777667776..
...668cc7768867788666...
......cc77cccc67cf......
......cc6cccccc6cf......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
